services:
  letta:
    image: letta/letta:latest@sha256:e6d74c3bf9911003fd326a1b2959ab2527520d6b16d2b63216fdf7ab9fb11d24
    container_name: letta
    profiles:
    - letta
    restart: unless-stopped
    volumes:
    - letta_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-}
      SECURE: ${LETTA_SECURE:-true}
      LETTA_SERVER_PASSWORD: ${LETTA_SERVER_PASSWORD:-}
    extra_hosts:
    - host.docker.internal:host-gateway
volumes:
  letta_data: {}
