services:
  letta:
    image: letta/letta:latest@sha256:e22f8d30c55aa767b772d8bc310a54b2c063c2772bbc91830f9c3ffac73fb3c2
    container_name: letta
    profiles:
    - letta
    restart: unless-stopped
    volumes:
    - letta_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-}
      SECURE: ${LETTA_SECURE:-true}
      LETTA_SERVER_PASSWORD: ${LETTA_SERVER_PASSWORD:-}
    extra_hosts:
    - host.docker.internal:host-gateway
volumes:
  letta_data: {}
