services:
  python-runner:
    image: python:3.11-slim@sha256:e88e9763f943ec1834f992a4b51e0f24500486803e8bc534e5767af9ea65f6ce
    container_name: python-runner
    env_file:
      - .env
    profiles:
    - python-runner
    restart: unless-stopped
    working_dir: /app
    command: /bin/sh -c 'if [ -f /app/requirements.txt ]; then python -m pip install
      --no-cache-dir -r /app/requirements.txt; fi; python /app/main.py'
    volumes:
    - .:/app

