services:
  python-runner:
    image: python:3.11-slim@sha256:9534e5a8e315485d4061ed659af0fd78a284c015f9b73661b41d6bab25604534
    container_name: python-runner
    env_file:
      - .env
    profiles:
    - python-runner
    restart: unless-stopped
    working_dir: /app
    command: /bin/sh -c 'if [ -f /app/requirements.txt ]; then python -m pip install
      --no-cache-dir -r /app/requirements.txt; fi; python /app/main.py'
    volumes:
    - .:/app

