services:
  portainer:
    image: portainer/portainer-ce:latest@sha256:511f3f06c96fe3b993ebeaafde311c1959cae73a7ef825dba6397d51b450dffa
    container_name: portainer
    env_file:
      - .env
    profiles:
    - portainer
    restart: unless-stopped
    volumes:
    - ./data:/data
    - ${DOCKER_SOCKET_LOCATION:-/var/run/docker.sock}:/var/run/docker.sock

# volumes:
#   portainer_data: {}
