services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main@sha256:1a6399d237dc392a2313e0ca826020b3fd5d22536357840eb63393d18dc8b924
    restart: unless-stopped
    container_name: open-webui
    profiles:
    - open-webui
    env_file:
      - .env
    environment:
    - OLLAMA_BASE_URL=http://ollama:11434
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - ./data:/app/backend/data

# volumes:
#   open-webui: {}
