services:
  crawl4ai:
    image: unclecode/crawl4ai:latest@sha256:84751dab794259db05d5bd4e5c766a8041a65f0554326e4516e620abdf2fa18b
    container_name: crawl4ai
    profiles:
    - crawl4ai
    restart: unless-stopped
    shm_size: 1g
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G

