services:
  crawl4ai:
    image: unclecode/crawl4ai:latest@sha256:9021b3cb5c6f12570bbcd5395638495e0a06969b3148e377b953d174af2ebc9b
    container_name: crawl4ai
    profiles:
    - crawl4ai
    restart: unless-stopped
    shm_size: 1g
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G

