services:
  private-dns:
    image: coredns/coredns:latest@sha256:7efd3c635b03efd68c4e8398fc45f0d993d0e9ab016f72c1cefb0fd6d01aa286
    container_name: private-dns
    profiles:
      - private-dns
    restart: unless-stopped
    env_file:
      - ./.env
    command: ["-conf", "/etc/coredns/Corefile"]
    volumes:
      - ./config/local/Corefile:/etc/coredns/Corefile:ro
    ports:
      - "${PRIVATE_DNS_TARGET_IP}:53:53/udp"
      - "${PRIVATE_DNS_TARGET_IP}:53:53/tcp"
    healthcheck:
      disable: true