services:
  qdrant:
    image: qdrant/qdrant@sha256:b7b0444c4c351c970b98e90a6f89c2ee4287c65b44e52b4cb503fa5b2aa927ad
    container_name: qdrant
    profiles:
    - qdrant
    restart: unless-stopped
    volumes:
    - qdrant_storage:/qdrant/storage
    env_file:
      - .env
    environment:
    - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}
    expose:
    - '6333'
volumes:
  qdrant_storage: {}
