FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt
COPY app.py test_app.py ./
CMD ["python", "-m", "unittest", "-v", "test_app"]
