services:
  landing-page:
    image: nginx:alpine@sha256:72ba65eb42c10344912a84ff42408db7d34f2feb642204570ab8fc5ffd29f1d3
    container_name: landing-page
    env_file:
      - .env
    profiles:
      - landing-page
    restart: unless-stopped
    volumes:
      - ./website:/usr/share/nginx/html:ro
    networks:
      default:
        aliases:
          - landing-page

