services:
  landing-page:
    image: nginx:alpine@sha256:df221db836e1754089190208cee7eeda94f233197056426eda74a43ab1abeac2
    container_name: landing-page
    env_file:
      - .env
    profiles:
      - landing-page
    restart: unless-stopped
    volumes:
      - ./website:/usr/share/nginx/html:ro
    networks:
      default:
        aliases:
          - landing-page

