services:
  smtp-relay:
    image: alpine/socat@sha256:c5a091e1e735a90aa941a5828529dbe6c6157407a8047a9aa473faa133361b82
    container_name: smtp-relay
    env_file:
      - .env
    profiles:
    - smtp-relay
    restart: unless-stopped
    command: tcp-listen:8025,fork,reuseaddr tcp-connect:mailserver:25
