services:
  mysql:
    image: mysql:8.4@sha256:6ea90827b1100f8f2ae306a539f86d2c264a26ed435a2a9f75551dd5c3aeb242
    container_name: mysql
    profiles:
    - mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE:-leantime}
    - MYSQL_USER=${MYSQL_USER:-leantime}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
    - mysql_data:/var/lib/mysql
    command: --character-set-server=UTF8MB4 --collation-server=UTF8MB4_unicode_ci
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
      - -h
      - localhost
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mysql_data: {}
